apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-dsd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-java-dsd-app
  template:
    metadata:
      labels:
        app: my-java-dsd-app
        admission.datadoghq.com/enabled: "false"
    spec:
      containers:
      - name: my-java-dsd-app
        image: docker.io/alidatadog/dummy-java-dsd-app:with-inode@sha256:a62e653e3c8e493611ba5841d3af94921edef0670776d0555fed9eecc2b50341
        imagePullPolicy: Always
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
